# Generated by Django 5.0 on 2024-01-18 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('jornada', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Insidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('cedula_insp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_insp', models.CharField(max_length=100)),
                ('apellido_insp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFaltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_estudiante', models.CharField(max_length=100)),
                ('cedula_inspector', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Registros de Faltas',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula_est', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_est', models.CharField(max_length=100)),
                ('apellido_est', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo.curso')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFaltasIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_estudiante', models.CharField(max_length=20)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.insidencia')),
                ('registro_faltas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.registrofaltas')),
            ],
        ),
        migrations.AddField(
            model_name='registrofaltas',
            name='insidencias',
            field=models.ManyToManyField(through='modulo.RegistroFaltasIncidencia', to='modulo.insidencia'),
        ),
    ]
