# Generated by Django 5.0 on 2024-01-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofaltasincidencia',
            name='cedula_estudiante',
            field=models.CharField(max_length=100),
        ),
    ]
