# Generated by Django 5.0 on 2024-01-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_alter_registrofaltasincidencia_cedula_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrofaltasincidencia',
            name='cedula_estudiante',
        ),
    ]
