# Generated by Django 5.0 on 2024-01-20 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0004_curso_paralelo_estudiante_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='seccion',
            field=models.CharField(choices=[('BASICA', 'BASICA'), ('', ''), ('', ''), ('', '')], default='NINGUNA', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrofaltas',
            name='cedula_estudiante',
            field=models.ForeignKey(default='999999999', on_delete=django.db.models.deletion.SET_DEFAULT, to='modulo.estudiante'),
        ),
    ]
