# Generated by Django 5.0 on 2024-01-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0005_inspector_seccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='activo',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='seccion',
            field=models.CharField(choices=[('INICIAL', 'INICIAL'), ('BASICA', 'BASICA'), ('BASICA ELEMENTAL', 'BASICA ELEMENTAL'), ('BASICA SUPERIOR', 'BASICA SUPERIOR'), ('BACHILLERATO', 'BACHILLERATO')], default='Ninguna', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrofaltas',
            name='cedula_estudiante',
            field=models.CharField(max_length=100),
        ),
    ]
