# Generated by Django 5.0 on 2024-01-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0007_alter_inspector_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('cod_periodo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
