# Generated by Django 5.0 on 2024-01-29 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0008_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofaltas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registrofaltas',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo.periodo'),
        ),
    ]
