# Generated by Django 5.0 on 2024-01-29 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0010_alter_registrofaltas_cedula_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofaltas',
            name='cedula_inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo.inspector', verbose_name='Inspectores'),
        ),
    ]
