# Generated by Django 5.0 on 2024-02-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0011_alter_registrofaltas_cedula_inspector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cedula_docente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(max_length=100)),
                ('apellido_docente', models.CharField(max_length=100)),
                ('jornada', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina')], default='Ninguna', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
