# Generated by Django 5.0 on 2024-02-23 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0012_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofaltas',
            name='cedula_docente',
            field=models.ForeignKey(default=9999999999, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo.docente', verbose_name='Docentes'),
        ),
    ]
