# Generated by Django 5.0 on 2024-08-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0015_curso_fecha_audit_docente_fecha_audit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=1)),
                ('fecha_audit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrofaltas',
            name='insidencias',
        ),
        migrations.AlterField(
            model_name='estudiantescursos',
            name='cod_seccion',
            field=models.CharField(choices=[('', 'Seleccione una Sección.'), ('INICIAL', 'INICIAL'), ('BASICA', 'BASICA'), ('BASICA ELEMENTAL', 'BASICA ELEMENTAL'), ('BASICA SUPERIOR', 'BASICA SUPERIOR'), ('BACHILLERATO', 'BACHILLERATO')], default='Ninguna', max_length=50),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='seccion',
            field=models.CharField(choices=[('', 'Seleccione una Sección.'), ('INICIAL', 'INICIAL'), ('BASICA', 'BASICA'), ('BASICA ELEMENTAL', 'BASICA ELEMENTAL'), ('BASICA SUPERIOR', 'BASICA SUPERIOR'), ('BACHILLERATO', 'BACHILLERATO')], default='Ninguna', max_length=50),
        ),
        migrations.AddField(
            model_name='registrofaltas',
            name='incidencias',
            field=models.ManyToManyField(through='modulo.RegistroFaltasIncidencia', to='modulo.incidencia'),
        ),
        migrations.AlterField(
            model_name='registrofaltasincidencia',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.incidencia'),
        ),
        migrations.DeleteModel(
            name='Insidencia',
        ),
    ]
